// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DB from "../DB.res.mjs";
import * as Utils from "../Utils.res.mjs";
import * as Config from "../Config.res.mjs";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.mjs";

async function insert_code(url, code) {
  Date.now();
  return await Core__Promise.$$catch(DB.short_link_coll.insertOne({
                  code: code,
                  url: url,
                  exp: ((Date.now() | 0) / 1000 | 0) + Math.imul(Config.time_limit_min, 60) | 0
                }), (function (exn) {
                Utils.log_err(exn);
                return Promise.resolve(undefined);
              })) !== undefined;
}

async function query_code_by_url(url) {
  return await Core__Promise.$$catch(DB.short_link_coll.findOne({
                  url: url
                }), (async function (exn) {
                Utils.log_err(exn);
              }));
}

async function query_url_by_code(code) {
  return await Core__Promise.$$catch(DB.short_link_coll.findOne({
                  code: code
                }), (async function (exn) {
                Utils.log_err(exn);
              }));
}

async function del_code_expired() {
  var now = (Date.now() | 0) / 1000 | 0;
  return await Core__Promise.$$catch(DB.short_link_coll.deleteMany({
                  exp: {
                    $lt: now
                  }
                }), (async function (exn) {
                Utils.log_err(exn);
              })) !== undefined;
}

export {
  insert_code ,
  query_code_by_url ,
  query_url_by_code ,
  del_code_expired ,
}
/* DB Not a pure module */
