// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DB from "../DB.res.mjs";
import * as Utils from "../Utils.res.mjs";
import * as Config from "../Config.res.mjs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.mjs";

async function insert_code(url, code) {
  var coll = DB.short_link_db.collection("url");
  Date.now();
  return await Core__Promise.$$catch(coll.insertOne({
                  code: code,
                  url: url,
                  exp: ((Date.now() | 0) / 1000 | 0) + Math.imul(Config.time_limit_min, 60) | 0
                }), (function (exn) {
                Utils.log_err(exn);
                return Promise.resolve(undefined);
              })) !== undefined;
}

function query_code() {
  return Js_exn.raiseError("F:\\projects\\short-link-next\\src\\model\\Code.res:26:597-602 - Todo");
}

function query_url() {
  return Js_exn.raiseError("F:\\projects\\short-link-next\\src\\model\\Code.res:27:626-631 - Todo");
}

function del_code_expired() {
  return Js_exn.raiseError("F:\\projects\\short-link-next\\src\\model\\Code.res:28:662-667 - Todo");
}

export {
  insert_code ,
  query_code ,
  query_url ,
  del_code_expired ,
}
/* DB Not a pure module */
