// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_exn from "rescript/lib/es6/js_exn.js";

function insert_ip() {
  return Js_exn.raiseError("/Users/shiu/interesting/short-link-next/src/model/IP.res:1:22-27 - Todo");
}

function delete_ip() {
  return Js_exn.raiseError("/Users/shiu/interesting/short-link-next/src/model/IP.res:2:50-55 - Todo");
}

function update_ip() {
  return Js_exn.raiseError("/Users/shiu/interesting/short-link-next/src/model/IP.res:3:78-83 - Todo");
}

function query_ip() {
  return Js_exn.raiseError("/Users/shiu/interesting/short-link-next/src/model/IP.res:4:105-110 - Todo");
}

export {
  insert_ip ,
  delete_ip ,
  update_ip ,
  query_ip ,
}
/* No side effect */
