// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DB from "../DB.res.mjs";
import * as Utils from "../Utils.res.mjs";
import * as Config from "../Config.res.mjs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.mjs";

function insert_ip() {
  return Js_exn.raiseError("/Users/shiu/interesting/short-link-next/src/model/IP.res:1:22-27 - Todo");
}

function delete_ip() {
  return Js_exn.raiseError("/Users/shiu/interesting/short-link-next/src/model/IP.res:2:50-55 - Todo");
}

async function update_ip(ip, count) {
  var ip_coll = DB.short_link_db.collection("ip");
  return await Core__Promise.$$catch(ip_coll.update_one({
                  ip: ip
                }, {
                  $set: {
                    count: count,
                    ip: ip,
                    exp: Utils.now() + Math.imul(Config.time_limit_min, 60) | 0
                  }
                }, {
                  upsert: true
                }), (async function (exn) {
                Utils.log_err(exn);
              })) !== undefined;
}

function query_ip() {
  return Js_exn.raiseError("/Users/shiu/interesting/short-link-next/src/model/IP.res:24:549-554 - Todo");
}

export {
  insert_ip ,
  delete_ip ,
  update_ip ,
  query_ip ,
}
/* DB Not a pure module */
