// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mongodb from "mongodb";

var uri = "mongodb+srv://bruce:yush241263Q@cluster0.irerjya.mongodb.net/?retryWrites=true&w=majority";

var short_link_client = new Mongodb.MongoClient(uri);

var short_link_db = short_link_client.db("short_link");

export {
  uri ,
  short_link_client ,
  short_link_db ,
}
/* short_link_client Not a pure module */
