// Generated by ReScript, PLEASE EDIT WITH CARE


function copy(text) {
  var el = document.createElement("textarea");
  el.value = text;
  var body = document.body;
  body.appendChild(el);
  el.select();
  document.execCommand("copy");
  el.remove();
}

export {
  copy ,
}
/* No side effect */
