// Generated by ReScript, PLEASE EDIT WITH CARE

import Link from "next/link";
import * as JsxRuntime from "react/jsx-runtime";

function MainLayout$Navigation(props) {
  return JsxRuntime.jsx("nav", {
              children: JsxRuntime.jsxs(Link, {
                    href: "/",
                    className: "flex items-center w-1/3",
                    children: [
                      JsxRuntime.jsx("img", {
                            className: "w-5",
                            src: "/static/short.svg"
                          }),
                      JsxRuntime.jsx("span", {
                            children: "Short",
                            className: "text-xl ml-2 align-middle font-semibold text-[#a92976]"
                          })
                    ]
                  }),
              className: "p-2 h-12 flex border-b border-gray-200 justify-between items-center text-sm"
            });
}

function MainLayout(props) {
  var minWidth = {
    minWidth: "20rem"
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx(MainLayout$Navigation, {}),
                      JsxRuntime.jsx("main", {
                            children: props.children,
                            className: "mt-4 mx-4"
                          })
                    ],
                    className: "max-w-5xl w-full lg:w-3/4 text-gray-900 font-base"
                  }),
              className: "flex lg:justify-center",
              style: minWidth
            });
}

var make = MainLayout;

export {
  make ,
}
/* next/link Not a pure module */
